### ISSUE TITLE
get_neighbors() no more exclude_self option?

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#1048]
The tests of the KMC code fails because the option exclude_self option was removed in:
https://github.com/pyiron/pyiron/pull/1015/

@samwaseda What is the alternative? 

```
======================================================================
745ERROR: test_collect (kmc.test_kmc.TestKMC)
746----------------------------------------------------------------------
747Traceback (most recent call last):
748  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
749    self.ham_input.write_input()
750  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
751    self.write_lattice_topology()
752  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 268, in write_lattice_topology
753    neighbors = self.structure.get_neighbors(num_neighbors=number_of_neighbors, exclude_self=True, t_vec=False)
754TypeError: get_neighbors() got an unexpected keyword argument 'exclude_self'
755
756======================================================================
757ERROR: test_input_control (kmc.test_kmc.TestKMC)
758----------------------------------------------------------------------
759Traceback (most recent call last):
760  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
761    self.ham_input.write_input()
762  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
763    self.write_lattice_topology()
764  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 268, in write_lattice_topology
765    neighbors = self.structure.get_neighbors(num_neighbors=number_of_neighbors, exclude_self=True, t_vec=False)
766TypeError: get_neighbors() got an unexpected keyword argument 'exclude_self'
767
768======================================================================
769ERROR: test_input_lattice (kmc.test_kmc.TestKMC)
770----------------------------------------------------------------------
771Traceback (most recent call last):
772  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
773    self.ham_input.write_input()
774  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
775    self.write_lattice_topology()
776  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 268, in write_lattice_topology
777    neighbors = self.structure.get_neighbors(num_neighbors=number_of_neighbors, exclude_self=True, t_vec=False)
778TypeError: get_neighbors() got an unexpected keyword argument 'exclude_self'
779
780======================================================================
781ERROR: test_input_structure (kmc.test_kmc.TestKMC)
782----------------------------------------------------------------------
783Traceback (most recent call last):
784  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
785    self.ham_input.write_input()
786  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
787    self.write_lattice_topology()
788  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 268, in write_lattice_topology
789    neighbors = self.structure.get_neighbors(num_neighbors=number_of_neighbors, exclude_self=True, t_vec=False)
790TypeError: get_neighbors() got an unexpected keyword argument 'exclude_self'
791
792======================================================================
793ERROR: tearDownClass (kmc.test_kmc.TestKMC)
794----------------------------------------------------------------------
795Traceback (most recent call last):
796  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 33, in tearDownClass
797    os.remove(os.path.join(cls.file_location, '../static/kmc_test_files.h5'))
798FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/pyiron/pyiron_mpie/tests/kmc/../static/kmc_test_files.h5'
799
800----------------------------------------------------------------------
```

**Comment by samwaseda** [comment]
There’s no option. ‘exclude_self’ is always ‘True’ (which is apparently also compatible with these tests - you just remove the argument and it’s gonna be fine)

**Comment by jan-janssen** [comment]
I tried this, now I get the following error: 

```
======================================================================
990ERROR: test_collect (kmc.test_kmc.TestKMC)
991----------------------------------------------------------------------
992Traceback (most recent call last):
993  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
994    self.ham_input.write_input()
995  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
996    self.write_lattice_topology()
997  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 272, in write_lattice_topology
998    f.write('{0:d} '.format(self.structure.max_nbr_number) + endline)
999  File "/home/travis/miniconda/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py", line 2536, in __getattr__
1000    return object.__getattribute__(self, item)
1001AttributeError: 'Atoms' object has no attribute 'max_nbr_number'
1002
1003======================================================================
1004ERROR: test_input_control (kmc.test_kmc.TestKMC)
1005----------------------------------------------------------------------
1006Traceback (most recent call last):
1007  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
1008    self.ham_input.write_input()
1009  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
1010    self.write_lattice_topology()
1011  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 272, in write_lattice_topology
1012    f.write('{0:d} '.format(self.structure.max_nbr_number) + endline)
1013  File "/home/travis/miniconda/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py", line 2536, in __getattr__
1014    return object.__getattribute__(self, item)
1015AttributeError: 'Atoms' object has no attribute 'max_nbr_number'
1016
1017======================================================================
1018ERROR: test_input_lattice (kmc.test_kmc.TestKMC)
1019----------------------------------------------------------------------
1020Traceback (most recent call last):
1021  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
1022    self.ham_input.write_input()
1023  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
1024    self.write_lattice_topology()
1025  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 272, in write_lattice_topology
1026    f.write('{0:d} '.format(self.structure.max_nbr_number) + endline)
1027  File "/home/travis/miniconda/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py", line 2536, in __getattr__
1028    return object.__getattribute__(self, item)
1029AttributeError: 'Atoms' object has no attribute 'max_nbr_number'
1030
1031======================================================================
1032ERROR: test_input_structure (kmc.test_kmc.TestKMC)
1033----------------------------------------------------------------------
1034Traceback (most recent call last):
1035  File "/home/travis/build/pyiron/pyiron_mpie/tests/kmc/test_kmc.py", line 24, in setUp
1036    self.ham_input.write_input()
1037  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 139, in write_input
1038    self.write_lattice_topology()
1039  File "/home/travis/build/pyiron/pyiron_mpie/pyiron_mpie/kmc/kmc.py", line 272, in write_lattice_topology
1040    f.write('{0:d} '.format(self.structure.max_nbr_number) + endline)
1041  File "/home/travis/miniconda/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py", line 2536, in __getattr__
1042    return object.__getattribute__(self, item)
1043AttributeError: 'Atoms' object has no attribute 'max_nbr_number'
```

**Comment by samwaseda** [comment]
Ok I’ll look into it tomorrow
