### ISSUE TITLE
Finished jobs show "aborted" status

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1105]
I did static VASP calculations. The OUTCARs show that they are successfully finished. But within pyiron status they are all "aborted". Anyone has some ideas about this? Thanks.

The error.out file (no error.msg file) is as following:
```
2020-10-27 14:09:53,525 - pyiron_log - INFO - run job: ham_3_19Ang_3400_0K_1_0_761304_test_262 id: 9988602, status: collect
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__main__.py", line 2, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/wrapper.py", line 39, in main
    submit_on_remote=args.submit
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 150, in job_wrapper_function
    job.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 116, in run
    self.job.run_static()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 788, in run_static
    self.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 699, in run
    self._run_if_collect()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 1485, in _run_if_collect
    self.collect_output()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/vasp/base.py", line 384, in collect_output
    directory=self.working_directory, sorted_indices=self.sorted_indices
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/vasp/base.py", line 1894, in collect
    self.outcar.from_file(filename=posixpath.join(directory, "OUTCAR"))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/vasp/outcar.py", line 66, in from_file
    e_fermi_list, vbm_list, cbm_list = self.get_band_properties(filename=filename, lines=lines)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron/vasp/outcar.py", line 814, in get_band_properties
    cbm_level_list.append(band_energy[np.abs(band_occ) < 1e-6][0])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by jan-janssen** [comment]
@lfzhu-phys Can you share an example `OUTCAR` file so we can test it?

**Comment by lfzhu-phys** [comment]
Thanks, Jan. Please check the attached OUTCAR.
[OUTCAR.gz](https://github.com/pyiron/pyiron/files/5446030/OUTCAR.gz)
