### ISSUE TITLE
ase version 3.20.1 incompatible with loading a job 

### ISSUE THREAD

**Issue by cmmmalik** [pyiron/pyiron#1108]
While doing ` pr.load_from_jobpath(jobid)` runs into an error because ase recent update (version 3.20.1) does not support 'pbc'  as an argument to ase.cell.Cell
```
>>> pr.load_from_jobpath(job_id=1)
{'array': array([[0.   , 2.025, 2.025],
       [2.025, 0.   , 2.025],
       [2.025, 2.025, 0.   ]]), 'pbc': array([ True,  True,  True])}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/am77cuxa/git_repository/pyiron/0.0.0/lib/python3.7/site-packages/pyiron-0.0.0-py3.7.egg/pyiron/project.py", line 233, in load_from_jobpath
    job_id=job_id, db_entry=db_entry, convert_to_object=convert_to_object
  File "/home/am77cuxa/git_repository/pyiron_base/0.0.0/lib/python3.7/site-packages/pyiron_base-0.1.23.post0.dev2-py3.7.egg/pyiron_base/project/generic.py", line 762, in load_from_jobpath
    convert_to_object=convert_to_object, project=job.project_hdf5.copy()
  File "/home/am77cuxa/git_repository/pyiron_base/0.0.0/lib/python3.7/site-packages/pyiron_base-0.1.23.post0.dev2-py3.7.egg/pyiron_base/job/core.py", line 541, in load_object
    return self.to_object(project=job_dir, job_name=self._name)
  File "/home/am77cuxa/git_repository/pyiron_base/0.0.0/lib/python3.7/site-packages/pyiron_base-0.1.23.post0.dev2-py3.7.egg/pyiron_base/job/core.py", line 480, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
  File "/home/am77cuxa/git_repository/pyiron_base/0.0.0/lib/python3.7/site-packages/pyiron_base-0.1.23.post0.dev2-py3.7.egg/pyiron_base/generic/hdfio.py", line 1319, in to_object
    group_name = self.h5_path.split('/')[-1]
  File "/home/am77cuxa/git_repository/pyiron/0.0.0/lib/python3.7/site-packages/pyiron-0.0.0-py3.7.egg/pyiron/gpaw/gpaw.py", line 193, in from_hdf
    super(Gpaw, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/home/am77cuxa/git_repository/pyiron/0.0.0/lib/python3.7/site-packages/pyiron-0.0.0-py3.7.egg/pyiron/gpaw/pyiron_ase.py", line 122, in from_hdf
    self.structure = self._fromdict(hdf_input["structure"])
  File "/home/am77cuxa/git_repository/pyiron/0.0.0/lib/python3.7/site-packages/pyiron-0.0.0-py3.7.egg/pyiron/gpaw/pyiron_ase.py", line 94, in _fromdict
    atoms_dict_copy["cell"] = self._cellfromdict(celldict=atoms_dict_copy["cell"])
  File "/home/am77cuxa/git_repository/pyiron/0.0.0/lib/python3.7/site-packages/pyiron-0.0.0-py3.7.egg/pyiron/gpaw/pyiron_ase.py", line 44, in _cellfromdict
    return Cell(**celldict)
TypeError: __init__() got an unexpected keyword argument 'pbc'

```
The same problem is encountered when submitting a job remotely to a HPC cluster. Because, it is unable to load the structure from the hdf.

**Comment by jan-janssen** [comment]
Just for me to understand this issue, you saved the job using an older ASE version an now you try to load it with a newer ASE version and then the loading fails, right? Because pyiron just calls `to_dict()` on the cell https://github.com/pyiron/pyiron/blob/master/pyiron/gpaw/pyiron_ase.py#L56 and previously this included the periodic boundaries https://gitlab.com/ase/ase/-/blob/ase-3.19.3/ase/cell.py#L72 but in the new version I am not even sure if this option is available. Can you check if you can save a new job?

**Comment by cmmmalik** [comment]
Yes, loading of the job fails if the saving and loading versions of ase are older and newer respectively. I can try saving and loading with the same new ase version. 
In the new version, the pbc option has been removed.

**Comment by jan-janssen** [comment]
Can you test the pull request https://github.com/pyiron/pyiron/pull/1111 as the `set_pbc()` function is called after the creation of the cell and we anyway save the cell separately we should be fine just dropping the `pbc` entry from the dictionary. 
https://gitlab.com/ase/ase/-/blob/ase-3.19.3/ase/atoms.py#L237

**Comment by cmmmalik** [comment]
> Just for me to understand this issue, you saved the job using an older ASE version an now you try to load it with a newer ASE version and then the loading fails, right? Because pyiron just calls `to_dict()` on the cell https://github.com/pyiron/pyiron/blob/master/pyiron/gpaw/pyiron_ase.py#L56 and previously this included the periodic boundaries https://gitlab.com/ase/ase/-/blob/ase-3.19.3/ase/cell.py#L72 but in the new version I am not even sure if this option is available. Can you check if you can save a new job?

So, using the new ase version to save and load the job works.

**Comment by cmmmalik** [comment]
> Can you test the pull request #1111 as the `set_pbc()` function is called after the creation of the cell and we anyway save the cell separately we should be fine just dropping the `pbc` entry from the dictionary.
> https://gitlab.com/ase/ase/-/blob/ase-3.19.3/ase/atoms.py#L237

**Comment by cmmmalik** [comment]
> Can you test the pull request #1111 as the `set_pbc()` function is called after the creation of the cell and we anyway save the cell separately we should be fine just dropping the `pbc` entry from the dictionary.
> https://gitlab.com/ase/ase/-/blob/ase-3.19.3/ase/atoms.py#L237

I'll test it.

**Comment by cmmmalik** [comment]
The #1111 request works fine.

**Comment by jan-janssen** [comment]
Perfect - I merge it once the tests finished, thanks again for testing and if you find further bugs do not hesitate to open more issues we are happy to support new users and new tools like GPAW.
