### ISSUE TITLE
Timeout error for script job

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#1312]
**Summary**

<
I get timeout error when I run my script job
>

**pyiron Version and Platform**

```
[DEFAULT]
TYPE = Postgres
HOST = pyiron-db-cmmc.esc.rzg.mpg.de
NAME = pyiron
USER = skanchar

JOB_TABLE = jobs_cmmc
TOP_LEVEL_DIRS = /cmmc/u
VIEWERUSER = cmmc_view

VIEWER_TABLE = jobs_cmmc_admin
RESOURCE_PATHS = /cmmc/u/skanchar/pyiron/pyiron-resources-cmmc, /cmmc/u/skanchar/pyiron/pyiron-resources-cmmc-p
otentiostat
```

**Expected Behavior**

<
I expect the default timeout to be None
>

**Actual Behavior**

<
But I think the timeout is set to 9999999. This is the error I get
```
subprocess.CalledProcessError: Command 'jupyter nbconvert --ExecutePreprocessor.timeout=9999999 --to notebook -
-execute /cmmc/u/skanchar/pyiron/projects/research/Mg_surfaces_solid_solns/Ca_solid_solns/Ca_in_Mg_0001_surface
/generating_all_configs/5_by_5/Ca_in_Mg_0001/structures_job_hdf5/structures_job/structures.ipynb' returned non-
zero exit status 1.
```
>

**Steps to Reproduce**

<
    structures_job = pr.create_job(pr.job_type.ScriptJob, 'structures_job')
    structures_job.script_path = 'structures.ipynb'
    structures_job.server.queue = 'cm'
    structures_job.server.run_time = 120000
    structures_job.server.cores = 40
    structures_job.run()
>

**Further Information, Files, and Links**

**Comment by jan-janssen** [comment]
Please post the `error.msg` file from the working directory - to me this sounds like your notebook crashed. Are you able to execute the notebook on the login node?

**Comment by sravankumarkb** [comment]
The notebook essentially creates structures and compares them with other structures by looking at all the combinations. 
I can run the notebook to the end on the login node for small systems.
For large systems, I cannot run my notebook to the end on the login node, because it takes too long. That is why I wanted to submit it as a job. 

Here is the ``` error.msg```

```
[NbConvertApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `NbConvertApp`.
[NbConvertApp] Converting notebook /cmmc/u/skanchar/pyiron/projects/research/Mg_surfaces_solid_solns/Ca_solid_solns/Ca_in_Mg_0001_surface/generating_all_configs/5_by_5/Ca_in_Mg_0001/structures_job_hdf5/structures_job/structures.ipynb to notebook
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 836, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/asyncio/futures.py", line 263, in __await__
    yield self  # This tells Task to wait for completion.
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
    future.result()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/asyncio/futures.py", line 176, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 498, in async_setup_kernel
    yield
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/asyncio/tasks.py", line 251, in __step
    result = coro.throw(exc)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 840, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3//bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 556, in async_execute
    self.set_widgets_metadata()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 501, in async_setup_kernel
    await self._async_cleanup_kernel()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 364, in _async_cleanup_kernel
    assert self.km is not None
AssertionError
```

**Comment by jan-janssen** [comment]
```
nbclient.exceptions.DeadKernelError: Kernel died
```
This sounds like the notebook just crashed. But there should be some more information, in which cell it happened and so on. Maybe you can check `error.out` but in general if the notebook crashes there is not much we can do from the pyiron side.

**Comment by sravankumarkb** [comment]
Is there a way to tweak the notebook execution options so that the timeout can be set to None? Thanks.
Maybe something like this 

```
ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
```
from this webpage

[https://nbconvert.readthedocs.io/en/latest/execute_api.html](url)

[https://nbconvert.readthedocs.io/en/latest/config_options.html](url)
[https://github.com/jupyter/nbconvert/pull/260](url)

**Comment by jan-janssen** [comment]
From my perspective a dead kernel is not related to a timeout.
