### ISSUE TITLE
No output files when doing VASP calculations using "job_type.ThermoIntDftEam"

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1360]
**The same calculations were fine two weeks ago. Now I use the same notebook and just add one temperature point. The job status shows the job is running, but there is no outputs, i.e., OUTCAR, and also no error.msg. Any suggestion or hint for this? Thanks a lot in advance. **

**pyiron Version and Platform**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by pmrv** [comment]
Can you check whether the job is still running on the queue from the command line with `squeue --me`?  If nothing shows up there, but the job status is still listed as running, that means the job crashed without pyiron noticing.  In that case check the job working directory for any log files and post them.  You can get the working directory from pyiron via `print(job.working_directory)`.  In any case also post the `pyiron.log` from the folder where your notebooks is running.

**Comment by lfzhu-phys** [comment]
@pmrv Thanks a lot for looking into it. Yes, the jobs were running in the queue, but no outputs and no warning information. I have removed all the running jobs and just submitted a test job. The problem remains. This test job is still running in the queue. 

**The pyiron.log from where the notebooks is running**:

2021-08-11 10:40:30,176 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_164445 id: None, status: initialized
2021-08-11 10:40:30,768 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_164445 id: 15523970, status: created
2021-08-11 10:40:30,856 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_164445 id: 15523970, status: created
2021-08-11 10:40:30,946 - pyiron_log - INFO - job: ham_4_11Ang_600_0K_1_0_164445 id: 15523970, status: submitted, submitted: queue id 2362036
2021-08-11 12:38:28,645 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_927694 id: None, status: initialized
2021-08-11 12:38:29,270 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_927694 id: 15524041, status: created
2021-08-11 12:38:29,459 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_927694 id: 15524041, status: created
2021-08-11 12:38:29,547 - pyiron_log - INFO - job: ham_4_11Ang_600_0K_1_0_927694 id: 15524041, status: submitted, submitted: queue id 2362059

**The pyiron.log in the working directory**:
2021-08-11 12:38:35,452 - pyiron_log - INFO - job: ham_4_11Ang_600_0K_1_0_927694 id: 15524041, status: submitted, run job (modal)

**The error.out in the working directory**:
2021-08-11 12:38:35,452 - pyiron_log - INFO - job: ham_4_11Ang_600_0K_1_0_927694 id: 15524041, status: submitted, run job (modal)

**Comment by lfzhu-phys** [comment]
Additionally, if I run the job locally in the folder with bash command line, it works well and gives all output.

**Comment by pmrv** [comment]
I can see the job still running on the queue.  In that case, no output is expected until it is finished, I suppose, unless it is taking significantly longer than expected.  How long does it take to run the job locally?  I'm not familiar with `ThermoIntDftEam`, but can have a look later.

**Comment by lfzhu-phys** [comment]
It was not like this two weeks ago. This job typically takes 24 hours or more using 40 cores. I normally check the phase transition by importing the OUTCARs in pyiron during the calculations. Is there any update on pyiron in the past one week?

**Comment by lfzhu-phys** [comment]
@pmrv This moment all my jobs have to be stopped because of this issue. Thank you very much for looking into it.

**Comment by jan-janssen** [comment]
@muh-hassani To me this sounds like an issue with the pyiron resources - Can you take a look?

**Comment by muh-hassani** [comment]
@jan-janssen, do you think something is wrong with the queuing setup?

**Comment by muh-hassani** [comment]
@lfzhu-phys, can you tell me which queue you have used? and can you please do another check? I suggest to run a separate job vasp/lammps on the same queue and see whether you still have the same issue. If the issue is with pyiron resources, new jobs should also fail to return an ouput. Of course, you should not use command line to submit this job and only use pyiron to submit it. You said the same notebook with minor changes was successful before, you can use the same notebook without the recent changes. 

I want to see where the issue lies, queueing configuration or a code-based bug due to a recent update? There has been no update recently to pyiron resources, which takes care of queuing configuration. 
Can you also check your quota? Sometimes exceeding the quota limits does not allow other packages to create new files. To check the quota you can use: `/usr/lpp/mmfs/bin/mmlsquota --block-size auto`

**Comment by lfzhu-phys** [comment]
@muh-hassani @jan-janssen Thank you very much. I have tested both "s_cmfe" and "p_cmfe" and they have the same issue. The quota limit is ok. 

I just found another issue. When I run the "melting" notebook on the server (using 8 cores) to evaluate the melting temperature of an empirical potential, it works well. But when I submitted it in the queue, it crashes. The error.msg is:

/u/system/SLES12/soft/pyiron/dev/pyiron-resources-cmmc/lammps/bin/run_lammps_2019.06.05_default_mpi.sh: line 3:  9970 Segmentation fault      mpiexec -n $1 lmp_mpi -in control.inp

Maybe this error can give some hints for the previous issue.

Thanks you all very much for spending time on it.

**Comment by lfzhu-phys** [comment]
Also, the melting notebook was working fine two weeks ago.

**Comment by jan-janssen** [comment]
> @jan-janssen, do you think something is wrong with the queuing setup?

I do not know but if it worked before I assume it is a configuration change, but that is hard to tell from remote.

**Comment by muh-hassani** [comment]
@jan-janssen, I checked and in the last three weeks there has been no change to the `mpi` package, but `libgomp` was updated three weeks ago from `9.3.0` to `11.1.0`, and since then there has been a couple of changes in the build number. 
To have a complete picture, via an email, Lifang wrote me that she was able to successfully submit the same vasp job to the cluster using the following job file:
```
#!/usr/bin/env bash
#SBATCH -J vasp.5.3.5
#SBATCH -n 40
#SBATCH -p s.cmfe
#SBATCH -t 4-00:00:00
#SBATCH --mem-per-cpu=3G
/u/bzg/Thermodynamics/vasp_analyze/INCAR_change.sh INCAR NPAR 4
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun -n $SLURM_NPROCS /u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018
``` 
I know the environment variables and vasp executables are different than what we have in the resource folder, but I thought it might be worth mentioning.
I will try the notebook tonight to get more details.

**Comment by muh-hassani** [comment]
In running the notebook, I got in the first try the error of permission denied to access the executable. I found out that in the `/u/system/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/run_thermointdfteam_0.01_mpi.sh` the following execuable was used (it is also available [here](https://github.com/eisenforschung/pyiron-resources-mpie/blob/master/thermodynamics/bin/run_thermointdfteam_0.01_mpi.sh)):
```
 /u/lfzhu/Thermodynamics_2018/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018
```
I don't think it is the way, it should be. But I created a backup of it and did the following. 
Since @lfzhu-phys used `/u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018` to successfully run his job (see the comment above), I changed the executable to this one. But again the status of the job was aborted. I checked the `error.out` file, and I found the following error:
```ERROR: using REF_TYPE=extern but no calculate_energy_and_forces script available

2021-08-12 23:20:57,991 - pyiron_log - INFO - run job: ham_4_11Ang_600_0K_1_0_801308 id: 15528165, status: collect
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__main__.py", line 2, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/cli/wrapper.py", line 39, in main
    submit_on_remote=args.submit
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 149, in job_wrapper_function
    job.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/wrapper.py", line 115, in run
    self.job.run_static()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 771, in run_static
    self.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/generic/util.py", line 213, in decorated
    return function(*args, **kwargs)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 682, in run
    self._run_if_collect()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_base/job/generic.py", line 1420, in _run_if_collect
    self.collect_output()
  File "/u/system/SLES12/soft/pyiron/dev/pyiron_mpie/pyiron_mpie/thermodynamics/thermointdfteam.py", line 96, in collect_output
    super(ThermoIntDftEam, self).collect_output()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/vasp/base.py", line 388, in collect_output
    directory=self.working_directory, sorted_indices=self.sorted_indices
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/vasp/base.py", line 1930, in collect
    self.outcar.from_file(filename=posixpath.join(directory, "OUTCAR"))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/vasp/outcar.py", line 55, in from_file
    n_atoms = self.get_number_of_atoms(filename=filename, lines=lines)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyiron_atomistics/vasp/outcar.py", line 781, in get_number_of_atoms
    raise ValueError()
ValueError
```
Unfortunately, since I am going on vacation from tomorrow afternoon, I can not dig deeper and I also do not have the expertise for debugging vasp errors. @pmrv, since you also have the notebook, can you take a closer look? 
maybe @lfzhu-phys can also comment on this error as well.

**Comment by lfzhu-phys** [comment]
@muh-hassani Thanks a lot. I have one question. I cannot modify the file "/u/system/soft/pyiron/dev/pyiron-resources-cmmc/thermodynamics/bin/run_thermointdfteam_0.01_mpi.sh", right? Why I see this file is using the executable under the path "/u/bzg/Thermodynamics/vasp_Langevin/vasp_5.3.5/vasp-stable-cmmc-08.03.2018", which is different than yours?

**Comment by muh-hassani** [comment]
@lfzhu-phys I changed it last night to be able to run the notebook. The original file has a 'backup_' prefix.

**Comment by muh-hassani** [comment]
The issue is solved. Maybe it is necessary to document it somewhere. 
Even with the new path for the executable, the error remained still on Lifang's account. Therefore, I wondered whether the issue is with her configuration files. The `~/.pyiron` file looked ok, but in the `~/.bashrc` file, three extra modules were loaded: `mkl`, `intel`, `impi`. After commenting out the lines corresponding to loading these modules, the problem was solved (of course after sourcing the `.bashrc` file and also restarting her jupyter server).
I guess there might be some inconsistencies between these modules and our conda packages.
