### ISSUE TITLE
pyiron in binder - jupyter and jupyterlab extensions throw an error

### ISSUE THREAD

**Issue by tnecnivkcots** [pyiron/pyiron#1417]
Dear colleagues,

**Summary**

I got an bug by using the setup in the [pyiron/binder](https://github.com/pyiron/pyiron/tree/master/binder) folder.

**pyiron Version and Platform**

[Our MPCDF Binder Instance](https://notebooks.mpcdf.mpg.de/binder/) and the recently available pyiron version.

**Expected Behavior**

Building the container without throwing errors.

**Actual Behavior**

Throwing error messages, related to jupyter and jupyter lab extentions (this as example shown below):
```
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Installing /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static -> nglview-js-widgets
Up to date: /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/index.js.map
Copying: /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static/208a290102a4ada58a04de354a1354d7.png -> /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/208a290102a4ada58a04de354a1354d7.png
Copying: /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static/bf27228a7d3957983584fa7698121ea1.png -> /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/bf27228a7d3957983584fa7698121ea1.png
Copying: /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static/971364734f3b603e5d363a2634898b42.png -> /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/971364734f3b603e5d363a2634898b42.png
Copying: /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static/a4c733ec4baef9ad3896d4e34a8a5448.png -> /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/a4c733ec4baef9ad3896d4e34a8a5448.png
Copying: /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static/0de3b51742ed3ac61435875bccd8973b.png -> /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/0de3b51742ed3ac61435875bccd8973b.png
Up to date: /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/extension.js
Up to date: /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/index.js
Copying: /srv/conda/envs/notebook/lib/python3.7/site-packages/nglview/static/73a1fd052c9d84c0ee0bea3ee85892ed.png -> /srv/conda/envs/notebook/share/jupyter/nbextensions/nglview-js-widgets/73a1fd052c9d84c0ee0bea3ee85892ed.png
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable nglview --py --sys-prefix
    
```
and in the log file in the temp folder of the container:
```
Node v14.19.1

Yarn configuration loaded.
> /usr/bin/npm pack nglview-js-widgets
npm notice 
npm notice 📦  nglview-js-widgets@3.0.1
npm notice === Tarball Contents === 
npm notice 1.2kB   LICENSE                                  
npm notice 2.5kB   lib/base.js                              
npm notice 4.8kB   lib/color.js                             
npm notice 25.4kB  lib/lib/colorpicker.min.js               
npm notice 5.8kB   src/lib/colorpicker.min.js               
npm notice 912B    lib/embed.js                             
npm notice 455B    src/embed.js                             
npm notice 1.1kB   lib/extension.js                         
npm notice 537B    src/extension.js                         
npm notice 3.9kB   lib/fullscreen.js                        
npm notice 156.9kB lib/gui.js                               
npm notice 61.4kB  src/gui.js                               
npm notice 4.2MB   dist/index.js                            
npm notice 1.5kB   lib/index.js                             
npm notice 21B     style/index.js                           
npm notice 1.2kB   lib/jupyterlab-plugin.js                 
npm notice 411B    src/jupyterlab-plugin.js                 
npm notice 11.7kB  lib/lib/signals.min.js                   
npm notice 3.2kB   src/lib/signals.min.js                   
npm notice 3.6kB   lib/theme.js                             
npm notice 65.9kB  lib/ui/ui.extra.js                       
npm notice 23.8kB  src/ui/ui.extra.js                       
npm notice 61.4kB  lib/ui/ui.js                             
npm notice 21.6kB  src/ui/ui.js                             
npm notice 22.6kB  lib/ui/ui.ngl.js                         
npm notice 8.0kB   src/ui/ui.ngl.js                         
npm notice 98.9kB  lib/widget_ngl.js                        
npm notice 3.0kB   package.json                             
npm notice 5.1MB   dist/index.js.map                        
npm notice 1.9kB   README.md                                
npm notice 3.8kB   dist/0de3b51742ed3ac61435875bccd8973b.png
npm notice 3.8kB   dist/208a290102a4ada58a04de354a1354d7.png
npm notice 3.8kB   dist/73a1fd052c9d84c0ee0bea3ee85892ed.png
npm notice 3.8kB   dist/971364734f3b603e5d363a2634898b42.png
npm notice 3.8kB   dist/a4c733ec4baef9ad3896d4e34a8a5448.png
npm notice 3.8kB   dist/bf27228a7d3957983584fa7698121ea1.png
npm notice 894B    src/base.ts                              
npm notice 2.0kB   src/color.ts                             
npm notice 1.6kB   src/fullscreen.ts                        
npm notice 555B    src/index.ts                             
npm notice 1.5kB   src/theme.ts                             
npm notice 42.6kB  src/widget_ngl.ts                        
npm notice === Tarball Details === 
npm notice name:          nglview-js-widgets                      
npm notice version:       3.0.1                                   
npm notice filename:      nglview-js-widgets-3.0.1.tgz            
npm notice package size:  1.9 MB                                  
npm notice unpacked size: 9.9 MB                                  
npm notice shasum:        9eb7a429bbd299b39708b6d878ee0c710ccfc2bf
npm notice integrity:     sha512-W+Z49CJNbqMWY[...]qIPe77dHuafGQ==
npm notice total files:   42                                      
npm notice 
nglview-js-widgets-3.0.1.tgz

Node v14.19.1

Yarn configuration loaded.
Building jupyterlab assets (production, not minimized)
> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning @blueprintjs/core@3.47.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.47.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.15.0" has unmet peer dependency "@types/react@^16.3.0 || ^17.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
success Saved lockfile.
Done in 35.44s.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.15.0" has unmet peer dependency "@types/react@^16.3.0 || ^17.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
Done in 3.05s.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.21.1
$ webpack --config webpack.prod.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve './base.css' in '/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style'
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1771:28
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:742:13
    at eval (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:276:22
    at eval (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:405:22
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:119:11
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:650:24
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:813:8
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:933:5
resolve './base.css' in '/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style'
  using description file: /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/package.json (relative path: ./style/base.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style/base.css doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style/base.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style/base.css.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style/base.css.wasm doesn't exist
      as directory
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/nglview-js-widgets/style/base.css doesn't exist
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 141, in start
    production = production, minimize = self.minimize, app_options=app_options)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 483, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 697, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: lab
```

**Steps to Reproduce**

1. copy the files in der [pyiron/binder](https://github.com/pyiron/pyiron/tree/master/binder) folder to a github/gitlab repository
2. use the new created repository for creating a binder instance, like [our MPCDF one](https://notebooks.mpcdf.mpg.de/binder/). Or maybe better another one, for beeing sure, the container image is newly builded.

**Further Information, Files, and Links**

I tried to use the postBuild file, without executing the commands:
```
# ngl view for jupyter
jupyter nbextension install nglview --py --sys-prefix
jupyter nbextension enable nglview --py --sys-prefix

# ngl view for jupyter lab
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install nglview-js-widgets --minimize=False
```

I already tried to use it and found no issues in displaying calculated figures.

**Comment by tnecnivkcots** [comment]
For what is the nglview exactly responsible in jupyterlab?

**Comment by niklassiemer** [comment]
You need nglview for our structure.plot3d method. However,  it might be that the newer jupyterlab install it in a different way without the need to by hand install the js components.

**Comment by tnecnivkcots** [comment]
I think @muh-hassani told me something like "nglview is not longer needed for jupyterhub" some months ago.

When I tried building it and using the water simulation example notebook, all 3d plots were correctly shown.

Should we delete that lines?

**Comment by muh-hassani** [comment]
@tnecnivkcots, you should keep nglview in the `environment.yml`, but delete the lines in the  [postBuild script](https://github.com/pyiron/pyiron/blob/master/binder/postBuild), where it tries to build the extensions ([this line](https://github.com/pyiron/pyiron/blob/4e6360ec84265129a68b8db6ead622165bc32e3e/binder/postBuild#L5) and [this one](https://github.com/pyiron/pyiron/blob/4e6360ec84265129a68b8db6ead622165bc32e3e/binder/postBuild#L6)). This step is not required anymore, since jupyterlab3.

**Comment by tnecnivkcots** [comment]
@muh-hassani thank you for your clearing words.
