### ISSUE TITLE
submitted jobs disappeared in the queue list

### ISSUE THREAD

**Issue by lfzhu-phys** [pyiron/pyiron#1421]
I have submitted some VASP jobs last week through pyiron. Most of them are finished or running. This morning I noticed that the jobs with "submitted" status disappeared in the queue list. By simply resubmitting the jobs seems not working. Is any one also experiencing this?

The error message is as following:
```
"Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/__main__.py", line 3, in <module>
    main()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/__init__.py", line 63, in main
    args.cli(args)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/cli/wrapper.py", line 31, in main
    job_wrapper_function(
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/wrapper.py", line 171, in job_wrapper_function
    job.run()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/wrapper.py", line 124, in run
    self.job.run_static()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/generic.py", line 745, in run_static
    if self.executable.executable_path == "":
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/job/executable.py", line 195, in executable_path
    if self.storage.executable_path is not None:
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/pyiron_base/generic/datacontainer.py", line 389, in __getattr__
    raise AttributeError(name) from None
AttributeError: executable_path"
  ```
Any suggestion for this? Thanks a lot in advance.

**Comment by lfzhu-phys** [comment]
Any update on this issue?

**Comment by lfzhu-phys** [comment]
The last time I submitted jobs were on 26th May. Most of the jobs are finished. The rest disappeared in the queue list with the above error. It seems some changes happened after 26th May. Any idea/suggestion is highly appreciated.

**Comment by niklassiemer** [comment]
Shortly before the mentioned date the latest pyiron_base release included 
Derive Executable from HasStorage (#728)
which I assume to be related.

**Comment by pmrv** [comment]
I believe this was fixed in this [PR](https://github.com/pyiron/pyiron_base/pull/763).  Please try again if the issue still happens.

**Comment by lfzhu-phys** [comment]
@pmrv @niklassiemer Thanks a lot. I will try to submit a few jobs and report it here later.

**Comment by lfzhu-phys** [comment]
Unfortunately, the error remains. Could someone please update it on the cluster? Thanks a lot in advance.

**Comment by pmrv** [comment]
Thanks for checking.  I'm a bit confused because @yuyuanjingxuan had the same issue over [here](https://github.com/pyiron/pyiron_atomistics/issues/639) and that was resolved now.  Did you restart the notebook or the server in the mean time?

**Comment by niklassiemer** [comment]
It now included in the newest release of pyiron_base and will be available on the cluster with the next update.

**Comment by lfzhu-phys** [comment]
@niklassiemer @pmrv @jan-janssen Thank you all very much! Just made a few tests and they are working now!!! Thanks:)

**Comment by niklassiemer** [comment]
Glad to hear that, however, AFAIK nothing changed on the cluster so far.

**Comment by lfzhu-phys** [comment]
@niklassiemer That means restarting the server is the key here:-))
