### ISSUE TITLE
`assert` in pyiron

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#1431]
These days, many classes of pyiron are used only for template purposes. For this, take a look at the following class:

```python
class Template:
    def __init__(self):
        self.status = 'initialized'

    def write_input(self):
        self.status = 'running'

    def run_static(self):
        self.status = 'collect'
        
    def collect_output(self):
        self.status = 'finished'

    def run(self):
        assert self.status == 'initialized'
        self.write_input()
        assert self.status == 'running'
        self.run_static()
        assert self.status == 'collect'
        self.collect_output()
        assert self.status == 'finished'
```

This is what people usually do in C++. As it is well explained in [this article](https://stats.stackexchange.com/questions/153823/what-is-verbose-in-scikit-learn-package-of-python), `assert` is not commonly used in python, mainly because we usually use unit tests (and also `assert` is not removed when the programme is in use). In particular, we would rather check the status inside the unit test and not within `def run` in the example above. However, if pyiron is to be used as a template, we want to make sure that the developers use functionalities correctly, meaning for example `def run` is not overwritten, `def write_input` is defined when an executive is set etc. So in this regard, the assertion tests in the example above actually make sense, and they can be hardly replaced by unit tests (at least from the pyiron side we cannot really offer anything). There's already the possibility of setting the logging level (which is right now hardly used), but as far as I know this one doesn't add extra checks, meaning we cannot perform extra assertion tests in the debug mode. I wanted to know your ideas or if you know a well established way I'd love to know it as well. And it might be a good idea to develop a common strategy as well.

**Comment by liamhuber** [comment]
I am not sure how I feel about that overall. I am definitely cautious, exactly because using `assert` is unorthodox. However, some of my reticence might be due to the specific example. I'm not super happy with our run flow to begin with, and in this particular case I think a much cleaner implementation looks like this:

```python

class Template(SomeJobBaseClassThatGivesMeLogIUseLater, ABC):
    def __init__(self):
        super().__init__()  # I guess?
        self.status = 'created'

    @abstractmethod
    def write_input(self):
        pass

    @abstractmethod
    def run_static(self):
        pass
   
    @abstractmethod
    def collect_output(self):
        pass


    def _write_input(self):
        self.status = 'initialized'
        self.write_input()

    def _run_static(self):
        self.status = 'running'
        self.run_static()   

    def _collect_output(self):
        self.status = 'collecting'
        self.collect_output()

    def run(self):
        self._write_input()
        try:
            self._run_static()
        except Error as e:
            self.status = 'aborted'
            self.log(e)
        self._collect_output()
        self.status = 'finished'
```

This way the user doesn't need to bother themselves with updating the status at all, the required methods for child classes are completely explicit, and what's happening in `run` is pretty easy to read (not that it's hard in your example, just that we do keep cleanliness).

I guess in general I lean towards "making it easier to use right/harder to use wrong" rather than "[making] sure that the developers use functionalities correctly". This is definitely something I feel a bit flexible about though, and would be curious to see more examples/other perspectives.

**Comment by samwaseda** [comment]
> This way the user doesn't need to bother themselves with updating the status at all, the required methods for child classes are completely explicit, and what's happening in `run` is pretty easy to read (not that it's hard in your example, just that we do keep cleanliness).

Well, the status was just an example to illustrate how I would have used `assert` in C++ to debug. The problem remains the same with your example if the user overwrites `_write_input`.

> I guess in general I lean towards "making it easier to use right/harder to use wrong" rather than "[making] sure that the developers use functionalities correctly".

But these are two completely different things.

`write_input` and `collect_output` are two extreme examples which are definitely meant for the child classes. There are however cases where the distinction is less clear, like `GenericError` (which is actually not generic at all). And the abstraction that you proposed might work if the functionality exists only in the template level and the child class, but there are cases, where the sub-template uses the functionality, like `validate_ready_to_run`, which is defined in `GenericJob`, but is used in `AtomisticGenericJob`. In that case it might become difficult for the user to know that they have to call `super()`, even though it says abstract method in the level of `GenericJob`.

In total, it's true that the first thing is to make it easier for the user to use pyiron as a template, but at the same time I still think it's important to be able to enter a debug mode where bunch of assertion tests can be performed.

**Comment by samwaseda** [comment]
Just to clarify:

- I'm not saying we should write `assert` as in my example class. I used it as an example because that's how it's used in C++, which is only included in the debug mode (i.e. mostly removed when the code is compiled).
- What I'm trying to propose with "assertion tests" is a set of tests, which the developer can execute when they implement a new class using pyiron as a template, which tells you the class is ready to go if all tests pass.

**Comment by liamhuber** [comment]
> What I'm trying to propose with "assertion tests" is a set of tests, which the developer can execute when they implement a new class using pyiron as a template, which tells you the class is ready to go if all tests pass.

Ahh, I think I misunderstood. I really thought you intended that this is how parent classes should be written. Because I really don't want a bunch of `assert`s kicking around the source code, e.g. in the case

> the problem remains the same with your example if the user overwrites _write_input.

my response is just "well, the user shouldn't overwrite that, and if they use any sort of IDE it's pretty easy for them to see that this method name is taken already".

On the other hand, some sort of wrapper that you can apply to a child which then runs tests (assertions or otherwise) make sure the child didn't inadvertently break the intended behaviour of the parent sounds quite appealing. I'm not sure quite how to write such a wrapper, but exposing something like following sounds helpful:

```python
from pyiron_atomistics.dev_tools import did_i_break_GenericAtomisticJob
did_i_break_GenericAtomisticJob(MySubclass)
> "No, you're cool"
```

ASIDE:

> In that case it might become difficult for the user to know that they have to call super(), even though it says abstract method in the level of GenericJob.

`abstractmethod` doesn't indicate that a `super` call is necessary, but that child classes need to implement this themselves. 

I'm not aware of any python tool for letting users know they really need to call super, which I think is a shame because sometimes you put methods in as a place-holder and intend the functionality to be totally overwritten as the child needs, and sometimes you put methods in which are a necessary foundation onto which children may only build.

**Comment by samwaseda** [comment]
> `abstractmethod` doesn't indicate that a `super` call is necessary, but that child classes need to implement this themselves.

The problem is `validate_ready_to_run` is marked `abstractmethod` in `GenericJob` but is overwritten in `AtomisticGenericJob`, meaning if the user wants to use its functionality in a class that's derived from `AtomisticGeneribJob`, they have to call `super()`, but this might become confusing if they see the function only in `GenericJob` and don't realise that it's overwritten in `AtomisticGenericJob`.

**Comment by pmrv** [comment]
Imo the expectation is that whenever you overwrite a method you should be calling `super()`.  Only when subclasses can make a compelling (and documented) case against it, it should not be done.  Though in those cases it usually indicates that the inheritance hierarchy is not well laid out.

**Comment by liamhuber** [comment]
> The problem is `validate_ready_to_run` is marked `abstractmethod` in `GenericJob` but is overwritten in `AtomisticGenericJob`, meaning if the user wants to use its functionality in a class that's derived from `AtomisticGeneribJob`, they have to call `super()`, but this might become confusing if they see the function only in `GenericJob` and don't realise that it's overwritten in `AtomisticGenericJob`.

Like Marvin, I am completely unconcerned by this. With any modern IDE it should be impossible to not find the relevant implementation of `validate_ready_to_run`. I.e. the following is a perfectly reasonable pattern:

```python
class Alpha(ABC):
    @abstractmethod
    def foo(self):
        pass

class Beta(Alpha, ABC):
    def foo(self):
        self.foo = "foo"

    @abstractmethod
    def give_a_number(self):
        pass

class Gamma(Beta):
    def foo(self):
        super().foo()
        self.bar = "bar"

    def give_a_number(self):
        return 42
```

You'd have to skip a step in the inheritance tree to miss the implemented call to `foo`. Control-clicking in any modern IDE ought to take you right to `Beta.foo`. Maybe this is a problem for our VIM-using dinosaurs? 😜 

One place it might get weird is with multiple inheritance, e.g. `class Delta(Alpha, Beta)`. But I think this is where Marvin's comment about the inheritance hierarchy being off come into play. E.g. I would be seriously concerned if someone made `class MyJob(GenericJob, AtomisticGenericJob)`. (Anyhow, in this particular case I think `super` will still function well because only one of the parents actually has something non-abstract implemented for `validate_ready_to_run`, but it could be a problem in other cases.)

I am still favourable towards supplying developers with some testing architecture (or at least some scaffolding) so they can see if their custom derived classes are working well. I agree devs might forget to call `super`, but I'm not worried about them tracking down what is being executed when they do call it.

**Comment by samwaseda** [comment]
> I am still favourable towards supplying developers with some testing architecture (or at least some scaffolding) so they can see if their custom derived classes are working well. I agree devs might forget to call `super`, but I'm not worried about them tracking down what is being executed when they do call it.

So you mean something like `did_i_break_GenericAtomisticJob` that you proposed? I just don't know what the function could possibly look like.

Btw. does your example above actually work? Can you actually assign `self.foo` inside `def foo`.

**Comment by liamhuber** [comment]
> So you mean something like `did_i_break_GenericAtomisticJob` that you proposed? I just don't know what the function could possibly look like.

Oh, nor I. But I think it's very worthwhile to mull over how we can increase testing support for developers who are building on pyiron outside this repo.

> Btw. does your example above actually work? Can you actually assign `self.foo` inside `def foo`?

🤦‍♂️ No, definitely not! Still, slap an underscore on the attribute assignments and we're ok 😂

**Comment by liamhuber** [comment]
So at the pyiron meeting on 2022-10-10 we (me, @jan-janssen, @pmrv, and @samwaseda, but edit this to add your name if you feel like I'm leaving you out! This is just who I remember actively participating in this sub-discussion) concluded that some sort of test case developers could pass their new test too was the way to go. Sam(?) additionally pointed out that we can even snag test cases from the regular pyiron test suite as needed, e.g. by putting wrappers on them in our special developer test case.

So here's my crack at what this might look like.

Somewhere in the codebase, we have a class that we intend people to subclass off of:
```python
from abc import ABC, abstractstaticmethod

class Foo(ABC):
    def __init__(self):
        self.foo = "foo"
        
    def bar_it(self):
        self.foo = "bar"
```

So then somewhere like `pyiron_base/pyiron_base/dev_tools/foo_tests.py` we have content like this:
```python
import unittest
from abc import ABC, abstractstaticmethod
from typing import Type

from pyiron_base.dev_tools.utils import test_user_class

class ChildrenOfFooTester(unittest.TestCase):
    def __init__(self, class_to_test, class_args=None, class_kwargs=None, methodName='runTest'):
        super().__init__(methodName=methodName)
        self.class_to_test = class_to_test
        self.class_args = class_args if class_args is not None else []
        self.class_kwargs = class_kwargs if class_kwargs is not None else {}
        
    def setUp(self):
        super().setUp()
        self.foo_child = self.class_to_test(*self.class_args, **self.class_kwargs)
        
    def test_fooness(self):
        with self.subTest("Initialization"):
            self.assertEqual(
                "foo", self.foo_child.foo, 
                msg=f"Expected foo attribute to be foo after __init__, but got {self.foo_child.foo}"
            )
        with self.subTest("bar_it behaviour"):
            try:
                self.foo_child.bar_it()
            except AttributeError:
                raise AttributeError("Children of Foo must have a `bar_it` method")
            self.assertEqual(
                "bar", self.foo_child.foo,
                msg=f"Expected foo attribute to be foo after bar_it, but got {self.foo_child.foo}"
            )  
            
    
def test_child_of_foo(class_to_test, class_args=None, class_kwargs=None):
    test_user_class(ChildrenOfFooTester, class_to_test, class_args=class_args, class_kwargs=class_kwargs)
```

Where the generic test function in `pyiron_base/pyiron_base/dev_tools/utls.py` is something I'm not totally happy with, but does the job:
```python
def test_user_class(class_tester, class_to_test, class_args=None, class_kwargs=None):
    suite = unittest.TestSuite()
    test_case = ChildrenOfFooTester(class_to_test, class_args=class_args, class_kwargs=class_kwargs)
    suite = unittest.TestSuite()
    test_methods = [method_name for method_name in class_tester.__dict__.keys() if method_name.startswith("test_")]
    for test_method in test_methods:
        # What? Do we really need to instantiate the class_tester a million times? There must be a better way
        suite.addTest(class_tester(class_to_test, class_args=class_args, class_kwargs=class_kwargs, methodName=test_method))
    runner = unittest.TextTestRunner()
    runner.run(suite)
```
(It took a while for me to sort out how to run children of `TestCase` with extra parameters, and I'm not at all confident that this is the most elegant solution!!!)

And we expose this in  `pyiron_base/pyiron_base/dev_tools/__init__.py`:
```python
from pyiron_base.dev_tools.foo_tests import test_child_of_foo
```

At this point, a dev playing around in a jupyter notebook can do the following:
```python
from pyiron_base import Foo
from pyiron_base.dev_tools import test_child_of_foo

class TotallyFine(Foo):
    def bar_it(self):
        super().bar_it()
        self.unrelated = "unrelated"
        
    def some_other_functionality(self):
        return {"Lord of the Rings": {"Extended edition": True}}
    
test_child_of_foo(TotallyFine)
>>> .
>>> ----------------------------------------------------------------------
>>> Ran 1 test in 0.006s
>>>
>>> OK

class BadBarIt(Foo):
    def __init__(self):
        super().__init__()
        self.another_property = 42
        
    def bar_it(self):
        self.foo = "my_illegal_custom_behaviour"

test_child_of_foo(BadBarIt)
>>> ======================================================================
>>> FAIL: test_fooness (__main__.ChildrenOfFooTester) [bar_it behaviour]
>>> ----------------------------------------------------------------------
>>> Traceback (most recent call last):
>>>   File "<ipython-input-41-2f65604919d7>", line 27, in test_fooness
>>>     self.assertEqual(
>>> AssertionError: 'bar' != 'my_illegal_custom_behaviour'
>>> - bar
>>> + my_illegal_custom_behaviour
>>>  : Expected foo attribute to be foo after bar_it, but got my_illegal_custom_behaviour
>>> 
>>> ----------------------------------------------------------------------
>>> Ran 1 test in 0.001s
>>> 
>>> FAILED (failures=1)
        

class PossiblyBadInit(Foo):
    def __init__(self, bad_input="foo"):
        super().__init__()
        self.foo = bad_input

test_child_of_foo(PossiblyBadInit)
>>> .
>>> ----------------------------------------------------------------------
>>> Ran 1 test in 0.006s
>>>
>>> OK

test_child_of_foo(PossiblyBadInit, class_kwargs={"bad_input": "not right at all"})
>>> ======================================================================
>>> FAIL: test_fooness (__main__.ChildrenOfFooTester) [Initialization]
>>> ----------------------------------------------------------------------
>>> Traceback (most recent call last):
>>>   File "<ipython-input-41-2f65604919d7>", line 18, in test_fooness
>>>     self.assertEqual(
>>> AssertionError: 'foo' != 'not right at all'
>>> - foo
>>> + not right at all
>>>  : Expected foo attribute to be foo after __init__, but got not right at all

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
```

There are improvements, like I can already see that `__init__` and `setUp` in `ChildrenOfFooTester` can actually be pulled out to a parent `ChildClassTester` so `ChildrenOfFooTester` really just holds the `test_*` methods. But I am pretty happy with the user interface, where you just import a method from `dev_tools` and throw your class (with optional args and kwargs) at it. Because we don't actually (yet!!!) allow passing a job's input to its initialization, this is an imperfect setup, but I wanted a test case that at least allowed args and kwargs to be passed to the class being tested.
