### ISSUE TITLE
pyscal version - ModuleNotFoundError: No module named 'pyscal'

### ISSUE THREAD

**Issue by Mateus-M-Reis** [pyiron/pyiron#1467]
pip installation failing.

I'm on a Xubuntu **22.04.2 LTS** x86_64 without GPU.
Trying to install `pyiron 0.4.7`.

I am using [pyenv ](https://github.com/pyenv/pyenv) and [virtualenvwrapper](https://github.com/python-virtualenvwrapper/virtualenvwrapper) to manage my python virtual environments:
```
mkvirtualenv pyiron            # python 3.10
pip install pyiron             # also tryied with pip install pyiron --pre
```

Moving on to download the pyiron resources:
```
python
>>> import pyiron
```

I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/pyiron/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/pyiron_atomistics/project.py", line 30, in <module>
    from pyiron_atomistics.lammps.potential import LammpsPotentialFile
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/pyiron_atomistics/lammps/__init__.py", line 1, in <module>
    from pyiron_atomistics.lammps.potential import view_potentials, list_potentials
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/pyiron_atomistics/lammps/potential.py", line 13, in <module>
    from pyiron_atomistics.atomistics.structure.atoms import Atoms
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/pyiron_atomistics/atomistics/structure/atoms.py", line 15, in <module>
    from structuretoolkit import (
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/structuretoolkit/__init__.py", line 5, in <module>
    from structuretoolkit.analyse.pyscal import (
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.11/site-packages/structuretoolkit/analyse/pyscal.py", line 7, in <module>
    import pyscal.core as pc
ModuleNotFoundError: No module named 'pyscal'
```

So I try to install `pyscal`:
```
>>> exit()
pip install pyscal
```
the following heappens:

```
Collecting pyscal
  Using cached pyscal-0.10.3-py2.py3-none-any.whl (138 kB)
Requirement already satisfied: matplotlib in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from pyscal) (3.7.1)
Requirement already satisfied: numpy in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from pyscal) (1.24.3)
Collecting openpyxl
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Requirement already satisfied: pandas in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from pyscal) (2.0.1)
Collecting scipy<1.9.3
  Using cached scipy-1.9.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.4 MB)
Collecting xlrd
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Requirement already satisfied: contourpy>=1.0.1 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (1.0.7)
Requirement already satisfied: cycler>=0.10 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (23.1)
Requirement already satisfied: pillow>=6.2.0 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (3.1.0b1)
Requirement already satisfied: python-dateutil>=2.7 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from matplotlib->pyscal) (2.8.2)
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: pytz>=2020.1 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from pandas->pyscal) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from pandas->pyscal) (2023.3)
Requirement already satisfied: six>=1.5 in ./.virtualenvs/pyiron/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->pyscal) (1.16.0)
Installing collected packages: xlrd, scipy, et-xmlfile, openpyxl, pyscal
  Attempting uninstall: scipy
    Found existing installation: scipy 1.10.1
    Uninstalling scipy-1.10.1:
      Successfully uninstalled scipy-1.10.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyiron-atomistics 0.2.66 requires scipy>=1.10.1, but you have scipy 1.9.2 which is incompatible.
structuretoolkit 0.0.1 requires scipy>=1.10.0, but you have scipy 1.9.2 which is incompatible.
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2 pyscal-0.10.3 scipy-1.9.2 xlrd-2.0.1
```
Which doesn't work:
```
python
>>> import pyiron
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/pyiron/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/pyiron_atomistics/project.py", line 30, in <module>
    from pyiron_atomistics.lammps.potential import LammpsPotentialFile
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/pyiron_atomistics/lammps/__init__.py", line 1, in <module>
    from pyiron_atomistics.lammps.potential import view_potentials, list_potentials
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/pyiron_atomistics/lammps/potential.py", line 13, in <module>
    from pyiron_atomistics.atomistics.structure.atoms import Atoms
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/pyiron_atomistics/atomistics/structure/atoms.py", line 15, in <module>
    from structuretoolkit import (
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/structuretoolkit/__init__.py", line 5, in <module>
    from structuretoolkit.analyse.pyscal import (
  File "/home/machinedr/.virtualenvs/pyiron/lib/python3.10/site-packages/structuretoolkit/analyse/pyscal.py", line 7, in <module>
    import pyscal.core as pc
ModuleNotFoundError: No module named 'pyscal.core'

```

More info:
```
pip list | grep pyiron
pyiron             0.4.7
pyiron-atomistics  0.2.66
pyiron-base        0.5.37

```

**Comment by jan-janssen** [comment]
@Mateus-M-Reis The easiest way to install pyiron is using the `conda-forge` community repositories: 
```
conda install -c conda-forge pyiron
```

Unfortunately, the `pyscal` package is not available on pypi https://github.com/pyscal/pyscal still you can install it using `pip`:
```
pip install git+https://github.com/srmnitc/pyscal.git
```

**Comment by jan-janssen** [comment]
@srmnitc Any chance you can publish pyscal on pypi ?
