### ISSUE TITLE
import pyiron error

### ISSUE THREAD

**Issue by mgt16-LANL** [pyiron/pyiron#1469]
**Summary**
```
<!--Please provide a clear and concise description of what the bug is.-->
>>> import pyiron
Traceback (most recent call last):
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/traitlets/traitlets.py", line 656, in get
    value = obj._trait_values[self.name]
KeyError: 'layout'
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/pyiron/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/pyiron_atomistics/project.py", line 34, in <module>
    from pyiron_atomistics.atomistics.structure.factory import StructureFactory
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/pyiron_atomistics/atomistics/structure/factory.py", line 39, in <module>
    from pyiron_atomistics.atomistics.structure.factories.materialsproject import (
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/pyiron_atomistics/atomistics/structure/factories/materialsproject.py", line 3, in <module>
    from pyiron_atomistics.atomistics.structure.has_structure import HasStructure
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/pyiron_atomistics/atomistics/structure/has_structure.py", line 12, in <module>
    import nglview
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/nglview/__init__.py", line 4, in <module>
    from . import adaptor, datafiles, show, widget
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/nglview/show.py", line 13, in <module>
    from .widget import NGLWidget
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/nglview/widget.py", line 19, in <module>
    from . import color, interpolate
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/nglview/color.py", line 114, in <module>
    ColormakerRegistry = _ColormakerRegistry()
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/nglview/base.py", line 10, in getinstance
    instances[cls] = cls()
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/nglview/color.py", line 44, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 480, in __init__
    self.open()
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 493, in open
    state, buffer_paths, buffers = _remove_buffers(self.get_state())
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 591, in get_state
    value = to_json(getattr(self, k), self)
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/traitlets/traitlets.py", line 703, in __get__
    return self.get(obj, cls)
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/traitlets/traitlets.py", line 659, in get
    default = obj.trait_defaults(self.name)
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/traitlets/traitlets.py", line 627, in default
    return self.make_dynamic_default()
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/ipywidgets/widgets/trait_types.py", line 168, in make_dynamic_default
    return self.klass(*(self.default_args or ()),
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 480, in __init__
    self.open()
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 511, in open
    self.comm = create_comm(**args)
  File "/Users/mgt16/miniconda3/envs/architector/lib/python3.10/site-packages/comm/__init__.py", line 27, in _create_comm
    raise NotImplementedError("Cannot ")
NotImplementedError: Cannot 
```
**pyiron Version and Platform**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by ligerzero-ai** [comment]
Any package which installs the `comm` package will trigger this error.

**Comment by ligerzero-ai** [comment]
`0.1.2` of `comm` will trigger this error

**Comment by mgt16-LANL** [comment]
I'd be fine with closing the issue.
