### ISSUE TITLE
Appveyor for python 2.7 

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#258]
This always keeps failing. Do we really need this? @jan-janssen

**Comment by jan-janssen** [comment]
The error message: 

```
======================================================================
529ERROR: atomistics.master.test_murnaghan_non_modal (unittest.loader.ModuleImportFailure)
530----------------------------------------------------------------------
531ImportError: Failed to import test module: atomistics.master.test_murnaghan_non_modal
532Traceback (most recent call last):
533  File "C:\Miniconda-x64\lib\unittest\loader.py", line 254, in _find_tests
534    module = self._get_module_from_name(name)
535  File "C:\Miniconda-x64\lib\unittest\loader.py", line 232, in _get_module_from_name
536    __import__(name)
537  File "C:\projects\pyiron\tests\atomistics\master\test_murnaghan_non_modal.py", line 2, in <module>
538    from pyiron.atomistics.structure.atoms import CrystalStructure
539  File "pyiron\__init__.py", line 4, in <module>
540    from pyiron.project import Project
541  File "pyiron\project.py", line 11, in <module>
542    from pyiron.base.project.generic import Project as ProjectCore
543  File "pyiron\base\project\generic.py", line 15, in <module>
544    from pyiron.base.generic.hdfio import ProjectHDFio
545  File "pyiron\base\generic\hdfio.py", line 14, in <module>
546    from tables.exceptions import NoSuchNodeError
547  File "C:\Miniconda-x64\lib\site-packages\tables\__init__.py", line 93, in <module>
548    from .utilsextension import (
549ImportError: DLL load failed: The specified module could not be found.
```

points to something being wrong with the version of pytables so I would assume it is going to be fixed in the next version, still for the time being it might be necessary to enforce a lower version.

**Comment by jan-janssen** [comment]
I tried enforcing potables 3.5.1 but that did not help https://github.com/pyiron/pyiron/tree/appveyor

**Comment by liamhuber** [comment]
![geek_and_poke_CI](https://user-images.githubusercontent.com/20283329/61136203-7335e280-a4c3-11e9-8b8a-f421b86a2eb5.jpg)
Courtesy of [geek & poke](http://geek-and-poke.com/geekandpoke/2010/10/26/geekpokes-list-of-best-practices-today-continuous-integratio.html)

**Comment by jan-janssen** [comment]
Fixed in https://github.com/pyiron/pyiron/pull/303
