### ISSUE TITLE
ase update: Can't import `Prism`

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#276]
It looks like the tests fail due to the absence of certain functions in the latest `ase` versions

```
Traceback (most recent call last):
  File "/Users/travis/build/pyiron/pyiron/tests/lammps/test_lammps.py", line 125, in test_lammps_water
    self.job_water.run(run_mode="manual")
  File "/Users/travis/build/pyiron/pyiron/pyiron/base/job/generic.py", line 580, in run
    self._run_if_new(debug=debug)
  File "/Users/travis/build/pyiron/pyiron/pyiron/base/job/generic.py", line 1054, in _run_if_new
    self._create_job_structure(debug=debug)
  File "/Users/travis/build/pyiron/pyiron/pyiron/base/job/generic.py", line 1281, in _create_job_structure
    self.write_input()
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/base.py", line 232, in write_input
    lmp_structure = self._get_lammps_structure(structure=self.structure, cutoff_radius=self.cutoff_radius)
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/base.py", line 738, in _get_lammps_structure
    lmp_structure.structure = structure
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/structure.py", line 189, in structure
    input_str = self.structure_full()
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/structure.py", line 345, in structure_full
    coords = self.rotate_positions(self._structure)
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/structure.py", line 536, in rotate_positions
    prism = UnfoldingPrism(self._structure.cell)
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/structure.py", line 81, in __init__
    apre[1, :], n1 = fold(apre[1, :], apre[0, :], 0)
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/structure.py", line 79, in fold
    return [float(self.f2qdec(vec_a)) for vec_a in (vec + n * pvec)], n
  File "/Users/travis/build/pyiron/pyiron/pyiron/lammps/structure.py", line 79, in <listcomp>
    return [float(self.f2qdec(vec_a)) for vec_a in (vec + n * pvec)], n
AttributeError: 'UnfoldingPrism' object has no attribute 'f2qdec'

```

**Comment by jan-janssen** [comment]
I added a workaround in https://github.com/pyiron/pyiron/pull/282 - still we have to fix this, so please keep the issue open.

**Comment by dnoeger** [comment]
Hi! I Also encountered this error when I installed `pyiron` on VSC-3 in Vienna
And tried to run the test mimization

`AttributeError: 'UnfoldingPrism' object has no attribute 'f2qdec'`

I checked to sources
and i checked the class's methods
`from ase.calculators.lammpsrun import Prism`
`from types import FunctionType`
`[k for k, v in Prism.__dict__.items() if isinstance(v, FunctionType)]`
yields
`['__init__',
 'get_lammps_prism',
 'update_cell',
 'vector_to_lammps',
 'vector_to_ase',
 'is_skewed']`
It seems that they moved the method the method
Here is the [implementation](https://github.com/grhawk/ASE/blob/master/ase/calculators/lammpsrun.py)

I added the function to the `UnfoldPrism` class as workaround until this issue is closed

**Comment by dnoeger** [comment]
Hi! I Also encountered this error when I installed `pyiron` on VSC-3 in Vienna
And tried to run the test mimization

`AttributeError: 'UnfoldingPrism' object has no attribute 'f2qdec'`

I checked to sources
and i checked the class's methods
`from ase.calculators.lammpsrun import Prism`
`from types import FunctionType`
`[k for k, v in Prism.__dict__.items() if isinstance(v, FunctionType)]`
yields
`['__init__',
 'get_lammps_prism',
 'update_cell',
 'vector_to_lammps',
 'vector_to_ase',
 'is_skewed']`
It seems that they moved the method the method
Here is the [implementation](https://github.com/grhawk/ASE/blob/master/ase/calculators/lammpsrun.py)

I added the function to the UnfoldPrism class as workaround until this issue is closed

**Comment by dnoeger** [comment]
Your 'UnfoldPrism' class never callls super constructor from `ase`'s `Prism` class therefore one should add 
`super(UnfoldingPrism, self).__init__(cell, pbc=pbc, tolerance=float('1e-{}'.format(digits)))` to the contructor

**Comment by sudarsan-surendralal** [comment]
Hi @dnoeger, thanks for the input! We made the changes [here](https://github.com/pyiron/pyiron/pull/310) (including your suggestion to use super to initialize the base class). 

FYI, ase hosts their repository on gitlab and not github  (https://gitlab.com/ase/ase). I think the repo you linked is a bit outdated
