### ISSUE TITLE
Tests failing 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#354]
On travis the Python 2.7 tests fail for mac os x and linux, even though they work on azure.

```
======================================================================
2161ERROR: test_install (base.settings.test_install.TestInstall)
2162----------------------------------------------------------------------
2163Traceback (most recent call last):
2164  File "/home/travis/build/pyiron/pyiron/tests/base/settings/test_install.py", line 24, in test_install
2165    '-p', os.path.join(self.execution_path, 'project')])
2166  File "pyiron/base/settings/install.py", line 143, in command_line
2167    git_folder_name=git_folder_name)
2168  File "pyiron/base/settings/install.py", line 103, in install_pyiron
2169    git_folder_name=git_folder_name)
2170  File "pyiron/base/settings/install.py", line 46, in _download_resources
2171    urllib2.urlretrieve(giturl_for_zip_file, temp_zip_file)
2172  File "/home/travis/miniconda/lib/python2.7/urllib.py", line 98, in urlretrieve
2173    return opener.retrieve(url, filename, reporthook, data)
2174  File "/home/travis/miniconda/lib/python2.7/urllib.py", line 245, in retrieve
2175    fp = self.open(url, data)
2176  File "/home/travis/miniconda/lib/python2.7/urllib.py", line 213, in open
2177    return getattr(self, name)(url)
2178  File "/home/travis/miniconda/lib/python2.7/urllib.py", line 443, in open_https
2179    h.endheaders(data)
2180  File "/home/travis/miniconda/lib/python2.7/httplib.py", line 1055, in endheaders
2181    self._send_output(message_body)
2182  File "/home/travis/miniconda/lib/python2.7/httplib.py", line 893, in _send_output
2183    self.send(msg)
2184  File "/home/travis/miniconda/lib/python2.7/httplib.py", line 855, in send
2185    self.connect()
2186  File "/home/travis/miniconda/lib/python2.7/httplib.py", line 1280, in connect
2187    server_hostname=server_hostname)
2188  File "/home/travis/miniconda/lib/python2.7/ssl.py", line 369, in wrap_socket
2189    _context=self)
2190  File "/home/travis/miniconda/lib/python2.7/ssl.py", line 599, in __init__
2191    self.do_handshake()
2192  File "/home/travis/miniconda/lib/python2.7/ssl.py", line 828, in do_handshake
2193    self._sslobj.do_handshake()
2194IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
2195
2196======================================================================
2197ERROR: tearDownClass (base.settings.test_install.TestInstall)
2198----------------------------------------------------------------------
2199Traceback (most recent call last):
2200  File "/home/travis/build/pyiron/pyiron/tests/base/settings/test_install.py", line 17, in tearDownClass
2201    shutil.rmtree(os.path.join(execution_path, 'resources'))
2202  File "/home/travis/miniconda/lib/python2.7/shutil.py", line 262, in rmtree
2203    onerror(os.listdir, path, sys.exc_info())
2204  File "/home/travis/miniconda/lib/python2.7/shutil.py", line 260, in rmtree
2205    names = os.listdir(path)
2206OSError: [Errno 2] No such file or directory: '/home/travis/build/pyiron/pyiron/tests/base/settings/resources'
2207
2208----------------------------------------------------------------------
```

It seems to be an issue with the travis SSL certificates.

**Comment by jan-janssen** [comment]
I guess as a temporary solution we can disable the Python 2.7 tests for now https://github.com/pyiron/pyiron/pull/362 and enable them again later on https://github.com/pyiron/pyiron/pull/363
