### ISSUE TITLE
Lammps Fe C example not working 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#388]
https://travis-ci.org/jan-janssen/release-testing/builds/580849202
```
[NbConvertApp] ERROR | Error while converting 'lammps-fe-c-example.ipynb'
958Traceback (most recent call last):
959  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
960    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
961  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
962    return self.from_file(f, resources=resources, **kw)
963  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
964    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
965  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
966    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
967  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
968    nb_copy, resources = self._preprocess(nb_copy, resources)
969  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
970    nbc, resc = preprocessor(nbc, resc)
971  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
972    return self.preprocess(nb, resources)
973  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
974    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
975  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
976    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
977  File "/home/travis/miniconda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
978    raise CellExecutionError.from_cell_and_msg(cell, out)
979nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
980------------------
981job.output.temperatures
982------------------
983
984---------------------------------------------------------------------------
985AttributeError                            Traceback (most recent call last)
986<ipython-input-15-212654ccf9a4> in <module>
987----> 1 job.output.temperatures
988
989AttributeError: 'GenericInteractiveOutput' object has no attribute 'temperatures'
990AttributeError: 'GenericInteractiveOutput' object has no attribute 'temperatures'
991
992
```

**Comment by jan-janssen** [comment]
Fixed in https://travis-ci.org/jan-janssen/release-testing/builds/580849202
