### ISSUE TITLE
Possible bug in list_nodes

### ISSUE THREAD

**Issue by dgehringer** [pyiron/pyiron#477]
Given is the attached hdf (rename it from *minimize.txt* to  [*minimize.h5*](https://github.com/pyiron/pyiron/files/3945912/minimize.txt)) file 
and the path to a **group** `minimize/graph/vertices/calc_static/archive/input/structure` 

However during deserialization in `from_hdf` method
`hdf.list_nodes()` of the parent path yields 
`['TYPE', 'interesting_keys', 'ref_job_full_path', 'structure']`

while **structure** is a group
I verified it with *HDFCompass* and `h5py` module which clearly states
```
import h5py
h = h5py.File('minimize.h5', 'r')
h['minimize/graph/vertices/calc_static/archive/input/structure']
```
`<HDF5 group "/minimize/graph/vertices/calc_static/archive/input/structure" (17 members)>`

**Comment by jan-janssen** [comment]
This is part of the pyiron philosophy, the objects which can be loaded are listed as nodes. The atomistic structure is an object, which the user should not access, therefore it is listed as `node` rather than `group`.

**Comment by dgehringer** [comment]
Yes but my `structure` is of `TYPE='<class 'collections.OrderedDict'>'` a custom defined complex type and but no `pyiron.atomistics.structure.atoms.Atoms` object

**Comment by dgehringer** [comment]
If I understand correctly, *pyiron* thinks it can load the group?
I get the error already when I try to lookup the `TYPE` e.g `hdf[key]['TYPE']` or if I use `project.inspect`


```
Traceback (most recent call last):
  File "/home/dominik/PycharmProjects/pyiron_contrib/pyiron_contrib/protocol/utils/dictionaries.py", line 259, in from_hdf
    setattr(self, key, hdf5_server[key])
  File "/home/dominik/.local/python/anaconda3/lib/python3.7/site-packages/pyiron/base/generic/hdfio.py", line 797, in __getitem__
    obj = h5io.read_hdf5(self.file_name, title=self._get_h5_path(item))
  File "/home/dominik/.local/python/anaconda3/lib/python3.7/site-packages/h5io/_h5io.py", line 261, in read_hdf5
    data = _triage_read(fid[title], slash=slash)
  File "/home/dominik/.local/python/anaconda3/lib/python3.7/site-packages/h5io/_h5io.py", line 279, in _triage_read
    data[key[4:]] = _triage_read(subnode, slash=slash)
  File "/home/dominik/.local/python/anaconda3/lib/python3.7/site-packages/h5io/_h5io.py", line 269, in _triage_read
    type_str = node.attrs['TITLE']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/dominik/.local/python/anaconda3/lib/python3.7/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'TITLE')"
```

**Comment by jan-janssen** [comment]
Can you load it with `h5io` directly? pyiron internally used `h5io` to access the HDF5 files and I am not sure if `OrderedDict` are supported, but `dict` in general works fine. It is always a question whether there is an mapping to an hdf5 data type.

**Comment by dgehringer** [comment]
Hi @jan-janssen !
At first many thanks for your quick, help. Yes I had a look on `h5io`, the problem occured when you want to serialize complex nested `dict`. e.g the values are *pyiron* structures.
I just prevented `hdf.__setitem__` for certain types that solved the issue for me.
Many thanks again
