### ISSUE TITLE
Strange sqlite error

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron#662]
One of my jobs crashed at the collect stage from the following sqllite error. Before I try to reproduce this, did anybody else encounter this before?

```
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute

sqlite3.OperationalError: no such column: elements.covalent_radius_slater

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/wrappercmd.py", line 52, in <module>
    command_line(sys.argv[1:])
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/wrappercmd.py", line 46, in command_line
    submit_on_remote=submit_on_remote
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/wrapper.py", line 147, in job_wrapper_function
    job.run()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/wrapper.py", line 113, in run
    self.job.run_static()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/master/serial.py", line 389, in run_static
    self._run_if_master_queue(job)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/master/serial.py", line 364, in _run_if_master_queue
    job.run()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 664, in run
    self._run_if_new(debug=debug)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/interactive.py", line 286, in _run_if_new
    super(VaspInteractive, self)._run_if_new(debug=debug)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 1307, in _run_if_new
    self.run()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 666, in run
    que_id = self._run_if_created()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 1324, in _run_if_created
    self.run_static()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 766, in run_static
    self.run()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 679, in run
    self._run_if_collect()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/base/job/generic.py", line 1395, in _run_if_collect
    self.collect_output()
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/base.py", line 392, in collect_output
    directory=self.working_directory, sorted_indices=self.sorted_indices
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/base.py", line 2046, in collect
    filename=posixpath.join(directory, "LOCPOT"), normalize=False
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/volumetric_data.py", line 50, in from_file
    filename=filename, normalize=normalize
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/volumetric_data.py", line 198, in _read_vol_data
    atoms = atoms_from_string(struct_lines)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/structure.py", line 217, in atoms_from_string
    atoms = _dict_to_atoms(atoms_dict, species_list=species_list)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/vasp/structure.py", line 314, in _dict_to_atoms
    atoms = Atoms(elements, scaled_positions=positions, cell=cell)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/atoms.py", line 188, in __init__
    el_object_list = [self.convert_element(el) for el in element_list]
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/atoms.py", line 188, in <listcomp>
    el_object_list = [self.convert_element(el) for el in element_list]
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/atoms.py", line 880, in convert_element
    element = Atom(el, pse=pse).element
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/atom.py", line 106, in __init__
    self._lists["element"] = pse.element(el_symbol)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/periodic_table.py", line 285, in element
    return ChemicalElement(element)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/periodic_table.py", line 47, in __init__
    self._init_mendeleev(self.sub.Abbreviation)
  File "/cmmc/u/chandu/programs/pyiron_mpie/pyiron/pyiron/atomistics/structure/periodic_table.py", line 65, in _init_mendeleev
    self._mendeleev_element = element(str(element_str))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/mendeleev/mendeleev.py", line 118, in element
    return _get_element(ids)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/mendeleev/mendeleev.py", line 133, in _get_element
    return session.query(Element).filter(Element.symbol == str(ids)).one()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3358, in one
    """
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3327, in one_or_none

  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3403, in __iter__
    if self._autoflush and not self._populate_existing:
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3428, in _execute_and_instances
    )
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: elements.covalent_radius_slater
[SQL: SELECT elements.electronic_configuration AS elements_electronic_configuration, elements.series_id AS elements_series_id, elements.abundance_crust AS elements_abundance_crust, elements.abundance_sea AS elements_abundance_sea, elements.annotation AS elements_annotation, elements.atomic_number AS elements_atomic_number, elements.atomic_radius AS elements_atomic_radius, elements.atomic_radius_rahm AS elements_atomic_radius_rahm, elements.atomic_volume AS elements_atomic_volume, elements.atomic_weight AS elements_atomic_weight, elements.atomic_weight_uncertainty AS elements_atomic_weight_uncertainty, elements.block AS elements_block, elements.boiling_point AS elements_boiling_point, elements.cas AS elements_cas, elements.covalent_radius_bragg AS elements_covalent_radius_bragg, elements.covalent_radius_cordero AS elements_covalent_radius_cordero, elements.covalent_radius_pyykko AS elements_covalent_radius_pyykko, elements.covalent_radius_pyykko_double AS elements_covalent_radius_pyykko_double, elements.covalent_radius_pyykko_triple AS elements_covalent_radius_pyykko_triple, elements.covalent_radius_slater AS elements_covalent_radius_slater, elements.c6 AS elements_c6, elements.c6_gb AS elements_c6_gb, elements.cpk_color AS elements_cpk_color, elements.density AS elements_density, elements.description AS elements_description, elements.dipole_polarizability AS elements_dipole_polarizability, elements.dipole_polarizability_unc AS elements_dipole_polarizability_unc, elements.discoverers AS elements_discoverers, elements.discovery_location AS elements_discovery_location, elements.discovery_year AS elements_discovery_year, elements.electron_affinity AS elements_electron_affinity, elements.en_allen AS elements_en_allen, elements.en_ghosh AS elements_en_ghosh, elements.en_pauling AS elements_en_pauling, elements.evaporation_heat AS elements_evaporation_heat, elements.fusion_heat AS elements_fusion_heat, elements.gas_basicity AS elements_gas_basicity, elements.geochemical_class AS elements_geochemical_class, elements.glawe_number AS elements_glawe_number, elements.goldschmidt_class AS elements_goldschmidt_class, elements.group_id AS elements_group_id, elements.heat_of_formation AS elements_heat_of_formation, elements.is_monoisotopic AS elements_is_monoisotopic, elements.is_radioactive AS elements_is_radioactive, elements.jmol_color AS elements_jmol_color, elements.lattice_constant AS elements_lattice_constant, elements.lattice_structure AS elements_lattice_structure, elements.melting_point AS elements_melting_point, elements.mendeleev_number AS elements_mendeleev_number, elements.metallic_radius AS elements_metallic_radius, elements.metallic_radius_c12 AS elements_metallic_radius_c12, elements.molcas_gv_color AS elements_molcas_gv_color, elements.name AS elements_name, elements.name_origin AS elements_name_origin, elements.period AS elements_period, elements.pettifor_number AS elements_pettifor_number, elements.proton_affinity AS elements_proton_affinity, elements.sources AS elements_sources, elements.specific_heat AS elements_specific_heat, elements.symbol AS elements_symbol, elements.thermal_conductivity AS elements_thermal_conductivity, elements.uses AS elements_uses, elements.vdw_radius AS elements_vdw_radius, elements.vdw_radius_alvarez AS elements_vdw_radius_alvarez, elements.vdw_radius_bondi AS elements_vdw_radius_bondi, elements.vdw_radius_truhlar AS elements_vdw_radius_truhlar, elements.vdw_radius_rt AS elements_vdw_radius_rt, elements.vdw_radius_batsanov AS elements_vdw_radius_batsanov, elements.vdw_radius_dreiding AS elements_vdw_radius_dreiding, elements.vdw_radius_uff AS elements_vdw_radius_uff, elements.vdw_radius_mm3 AS elements_vdw_radius_mm3
FROM elements
WHERE elements.symbol = ?]
[parameters: ('H',)]
(Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by jan-janssen** [comment]
I would assume it is an error with the file system and therefore more or less random. Were you able to reproduce this error?

**Comment by sudarsan-surendralal** [comment]
> I would assume it is an error with the file system and therefore more or less random. Were you able to reproduce this error?

No, I couldn't. It worked once I tried to collect the output again. This means that is could be due to the file system as you said. I'll close this issue for now but if someone encounters this more often feel free to reopen this!
