### ISSUE TITLE
Latest phonopy version fails to import spglib

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron#781]
```
======================================================================
2020-07-21T14:34:09.5880652Z ERROR: test_check_setup (sphinx.test_base.TestSphinx)
2020-07-21T14:34:09.5881405Z ----------------------------------------------------------------------
2020-07-21T14:34:09.5881754Z Traceback (most recent call last):
2020-07-21T14:34:09.5882107Z   File "/home/vsts/work/1/s/tests/sphinx/test_base.py", line 348, in test_check_setup
2020-07-21T14:34:09.5882475Z     self.assertFalse(self.sphinx.check_setup())
2020-07-21T14:34:09.5882917Z   File "/home/vsts/work/1/s/pyiron/sphinx/base.py", line 1411, in check_setup
2020-07-21T14:34:09.5883652Z     if self.get_n_ir_reciprocal_points() < self.server.cores:
2020-07-21T14:34:09.5884167Z   File "/home/vsts/work/1/s/pyiron/sphinx/base.py", line 1345, in get_n_ir_reciprocal_points
2020-07-21T14:34:09.5884519Z     from phonopy.structure import spglib
2020-07-21T14:34:09.5885322Z ImportError: cannot import name 'spglib' from 'phonopy.structure' (/usr/share/miniconda/envs/pyiron/lib/python3.7/site-packages/phonopy/structure/__init__.py)
2020-07-21T14:34:09.5885689Z 
2020-07-21T14:34:09.5886129Z ----------------------------------------------------------------------
```

**Comment by samwaseda** [comment]
This doesn't happen to me

**Comment by jan-janssen** [comment]
It happens with phonopy 2.7.0 which was release 19 hours ago https://anaconda.org/conda-forge/phonopy

**Comment by samwaseda** [comment]
How can I make it visible on the cluster?

**Comment by jan-janssen** [comment]
Currently I only see it in the automated unit tests on azure. Most likely the phonopy developers just changed the import path. Anyway it might be better for us to import the spglib directly rather than via phonopy. https://github.com/pyiron/pyiron/blob/master/pyiron/atomistics/structure/atoms.py#L28
```
import spglib
```
rather than 
```
from phonopy.structure import spglib
```
