### ISSUE TITLE
Issue with running pyiron

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron#947]
Hi all,

I am not sure what the cause is, but I am not being able to run even simple cells in pyiron, it takes forever on jupyter lab and I just see the "*" symbol next to the cell.

When I tried to run the notebooks on jupyter notebook, I see the following kernel error. Usually, it runs with the number of notebooks I have running right now. Any help is greatly appreciated, thanks.

```
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 314, in start_kernel
    self.post_start_kernel(**kw)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 295, in post_start_kernel
    self._connect_control_socket()
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 226, in _connect_control_socket
    self._control_socket = self._create_connected_socket('control')
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/jupyter_client/connect.py", line 545, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/zmq/sugar/context.py", line 226, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 59, in __init__
    super(Socket, self).__init__(*a, **kw)
  File "zmq/backend/cython/socket.pyx", line 328, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
```

**Comment by sravankumarkb** [comment]
I faced this temporarily for about five minutes. But, it is working now.
